### ISSUE TITLE
WAE samples are not as good as those in the appendix.

### ISSUE THREAD

**Issue by miskcoo** [ermongroup/sliced_score_matching#1]
Hi all,

I tried to run WAE on MNIST, using the parameters in `wae/mnist_ssm.yml`. However, the output images (see below) are not as good as those plotted in your appendix. 

![individualImage](https://user-images.githubusercontent.com/4351180/64037583-880c2980-cb88-11e9-9ee9-6166bfc12cae.png)

The command to run WAE is:
`python main.py --runner WAERunner --config wae/mnist_ssm.yml`

I am wondering if there is something wrong with me?

Thanks!

**Comment by yang-song** [comment]
Hi @miskcoo, I tried to rerun our program and got the following samples, which look comparable to those reported in the original paper. 

![image_grid](https://user-images.githubusercontent.com/7480450/64079801-e4fb0300-cca0-11e9-97d8-ad1da4277380.png)

I first ran the command
```
python main.py --runner WAERunner --config wae/mnist_ssm.yml
```
and then tested using
```
python main.py --runner WAERunner --config wae/mnist_ssm.yml --test
```

Without further details I cannot conclude why your samples look inferior.

**Comment by miskcoo** [comment]
Hi @yang-song, I checked again and found I made a mistake :(

The output was obtained after changing the activation function in `wae.MLPDecoder`, `wae.MLPEncoder` and `wae.MLPScore` to ReLU.

**Comment by yang-song** [comment]
Glad that you fixed the problem!
