### ISSUE TITLE
Question about "preprocess"

### ISSUE THREAD

**Issue by zanghyu** [ermongroup/sliced_score_matching#2]
Hi all,
I am trying to run the code, but I found that it seems [Link](https://github.com/ermongroup/sliced_score_matching/blob/master/runners/vae_runner.py#L143) do some process about the input data. I'm not familiar with the models training on MNIST, I wonder if it is an ordinary preprocess of the data, why should we do this before feeding them into the model?

**Comment by yang-song** [comment]
That line turns continuous MNIST to (dynamically) binarized MNIST for VAE modeling. It is standard in the literature.

**Comment by zanghyu** [comment]
Thanks!
